name: BoxArt
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: "Install yarn"
        run: npm install yarn

      - name: "Install dependencies"
        run: yarn install

      - name: "Build app"
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BOXART_TOKEN }}
          publish_dir: ./public
